import { ProductData } from './types';

const GITHUB = 'https://github.com/OrionArchitekton/reprise';
const GENBLAZE = 'https://github.com/backblaze-labs/genblaze';

/**
 * Single source of truth for the Reprise microsite.
 *
 * Every claim here is GROUNDED in the project README and eval/report.md. The
 * routing counts in the demo block are the labeled dataset's own numbers,
 * regenerated by tools/run_eval.py, with CI failing if they drift from the
 * generator. Do not hand-edit a number here; re-derive it from the report.
 */
export const PRODUCT_DATA: ProductData = {
  name: 'Reprise',
  tagline: 'Check what you already generated before you pay to generate it again.',
  credibility:
    'A reuse-first gateway for generative media, in front of Backblaze B2 · Python · built for the Backblaze Generative Media Hackathon 2026.',
  canonical: 'https://www.danmercede.com/works/reprise/',
  metaDescription:
    'Reprise sits in front of a Genblaze pipeline and answers one question per request: did we already generate this? If yes it serves the stored asset from Backblaze B2 and books the money not re-spent.',

  problem: {
    heading: 'The problem',
    body:
      'Every generative-media team quietly regenerates assets it already paid for. The same product shot, the same jingle, the same hero image with the same prompt, weeks apart, by different people. The spend is invisible because nothing in the pipeline is looking for the repeat.',
  },

  whatItDoes: {
    heading: 'What it does',
    body:
      'Reprise answers one question per request: did we already generate this? An exact match is served straight from B2 at zero cost with the saving booked. Otherwise the prompt is embedded and scored against the library: a similarity at or above 0.97 auto-serves the stored asset, anything from 0.85 to 0.97 goes to a human for a one-click decision, and only below 0.85 does it actually generate. Every decision is written to an Object-Lock ledger in B2 under GOVERNANCE retention, so the savings scoreboard is recomputed from records nobody can edit or destroy while retention holds.',
  },

  cta: {
    primaryLabel: 'View on GitHub',
    primaryUrl: GITHUB,
    secondaryLabel: 'Built on Genblaze',
    secondaryUrl: GENBLAZE,
  },

  quickstart: {
    heading: 'Reproduce the evaluation',
    intro:
      'The routing thresholds are not asserted, they are evaluated against a labeled dataset with live embeddings. The report regenerates from the same generator CI checks against.',
    blocks: [
      {
        title: 'Clone and regenerate the eval report',
        command:
          'git clone https://github.com/OrionArchitekton/reprise.git\ncd reprise\npython3 tools/run_eval.py',
      },
    ],
  },

  commands: [
    {
      name: 'REUSE',
      description:
        'Exact match, or similarity at or above 0.97. The stored asset is served from B2, nothing is generated, and the saving is booked to the ledger.',
    },
    {
      name: 'REVIEW',
      description:
        'Similarity between 0.85 and 0.97. Close enough to be worth a look, not close enough to auto-serve, so a human decides in one click.',
    },
    {
      name: 'GENERATE',
      description:
        'Below 0.85. Genuinely new work, so it runs the Genblaze pipeline and writes the result plus its provenance manifest back to B2.',
    },
  ],

  demo: {
    heading: 'Measured, not promised',
    intro:
      'The acceptance thresholds are evaluated against a labeled dataset using live gemini-embedding-001 embeddings. These are the report rows, not an illustration.',
    lines: [
      { kind: 'comment', text: 'category                          n   reuse  review  generate' },
      { kind: 'output', text: 'exact repeat                       6     6       0        0', tone: 'ok' },
      { kind: 'output', text: 'equivalent phrasing               10     5       5        0' },
      { kind: 'output', text: 'attribute swap (red to blue)      10     0       9        1' },
      { kind: 'output', text: 'same domain, different ask         7     0       0        7' },
      { kind: 'output', text: 'unrelated                          5     0       0        5', tone: 'ok' },
      { kind: 'comment', text: 'CI fails if these drift from the generator' },
    ],
  },

  differentiators: {
    heading: 'Why this is different',
    points: [
      {
        title: 'The cheapest generation is the one you skip',
        body:
          'Most cost tooling reports spend after the fact. Reprise sits in the request path and prevents the duplicate before it is billed.',
      },
      {
        title: 'A ledger nobody can quietly fix',
        body:
          'Savings are recomputed from an Object-Lock ledger under GOVERNANCE retention in B2. While retention holds, the records backing the scoreboard cannot be edited or destroyed, including by the app that wrote them.',
      },
      {
        title: 'Receipts you can re-derive',
        body:
          'Every result carries a run id, the manifest key and its canonical hash, a content-addressed asset key, a sha256, the producing model, and the retention actually in force. Those are coordinates you can check against the bucket, not a badge the app issues about itself.',
      },
      {
        title: 'Three outcomes, not a confidence score',
        body:
          'The bands are explicit and the middle band routes to a person. A near-miss is never silently served as a match.',
      },
    ],
  },

  links: [
    { label: 'GitHub repository', url: GITHUB, primary: true },
    { label: 'Genblaze', url: GENBLAZE },
    { label: 'More work by Dan Mercede', url: 'https://www.danmercede.com/works/' },
  ],

  footerNote:
    'Built for the Backblaze Generative Media Hackathon 2026. Judging status is whatever the organizer has published; no placement is claimed here.',
};
